/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GVB.Modulos.Menu.Vista;



import javax.swing.UIManager;

/**
 *
 * @author Vinche
 */
public class Ventana_ppal extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_ppal
     */
    public Ventana_ppal() {
        try{
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        }catch(Exception e){}
        initComponents();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEmpleados = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnPedidos = new javax.swing.JButton();
        btnReservas = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GVB/img/maletin.png"))); // NOI18N
        btnEmpleados.setText("Empleados");
        btnEmpleados.setMaximumSize(new java.awt.Dimension(100, 23));
        btnEmpleados.setMinimumSize(new java.awt.Dimension(100, 23));
        btnEmpleados.setOpaque(false);
        btnEmpleados.setPreferredSize(new java.awt.Dimension(100, 23));
        btnEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadosActionPerformed(evt);
            }
        });
        getContentPane().add(btnEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 41, 140, 60));

        btnProductos.setText("Productos");
        btnProductos.setMaximumSize(new java.awt.Dimension(100, 23));
        btnProductos.setMinimumSize(new java.awt.Dimension(100, 23));
        btnProductos.setOpaque(false);
        btnProductos.setPreferredSize(new java.awt.Dimension(100, 23));
        getContentPane().add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 140, 60));

        btnPedidos.setText("Pedidos");
        btnPedidos.setMaximumSize(new java.awt.Dimension(100, 23));
        btnPedidos.setMinimumSize(new java.awt.Dimension(100, 23));
        btnPedidos.setOpaque(false);
        btnPedidos.setPreferredSize(new java.awt.Dimension(100, 23));
        getContentPane().add(btnPedidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 140, 60));

        btnReservas.setText("Reservas");
        btnReservas.setMaximumSize(new java.awt.Dimension(100, 23));
        btnReservas.setMinimumSize(new java.awt.Dimension(100, 23));
        btnReservas.setOpaque(false);
        btnReservas.setPreferredSize(new java.awt.Dimension(100, 23));
        getContentPane().add(btnReservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 140, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GVB/img/fondo_degradado.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosActionPerformed

    }//GEN-LAST:event_btnEmpleadosActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnEmpleados;
    public static javax.swing.JButton btnPedidos;
    public static javax.swing.JButton btnProductos;
    public static javax.swing.JButton btnReservas;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
