/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GVB.Modulos.GestionLogin.Vista;

/**
 *
 * @author Vinche
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        TxtPass = new javax.swing.JPasswordField();
        TxtUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Entrar = new javax.swing.JButton();
        Registrarse = new javax.swing.JLabel();
        OlvidPass = new javax.swing.JLabel();
        NoPass = new javax.swing.JLabel();
        NoUsuario = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, new java.awt.Color(51, 255, 51)));
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxtPass.setBorder(null);
        jLayeredPane1.add(TxtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 222, 184, -1));

        TxtUsuario.setToolTipText("Introduce tu nombre de Usuario o Email");
        TxtUsuario.setBorder(null);
        jLayeredPane1.add(TxtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 139, 184, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Login");
        jLayeredPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, 256, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Usuario / Email");
        jLayeredPane1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 114, 116, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Password");
        jLayeredPane1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 197, 67, -1));

        Entrar.setText("Entrar");
        Entrar.setOpaque(false);
        jLayeredPane1.add(Entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(179, 270, -1, -1));

        Registrarse.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        Registrarse.setForeground(java.awt.Color.blue);
        Registrarse.setText("Registrarse");
        jLayeredPane1.add(Registrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 274, 84, -1));

        OlvidPass.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        OlvidPass.setForeground(java.awt.Color.blue);
        OlvidPass.setText("¿Olvidaste tu contraseña?");
        jLayeredPane1.add(OlvidPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 315, -1, -1));

        NoPass.setForeground(java.awt.Color.red);
        NoPass.setText("El usuario y la contraseña no coinciden");
        jLayeredPane1.add(NoPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 248, -1, -1));

        NoUsuario.setForeground(java.awt.Color.red);
        NoUsuario.setText("Usuario no registrado");
        jLayeredPane1.add(NoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 165, -1, -1));

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 30, 280, 380));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GVB/img/fondo_degradado2.jpeg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -9, 380, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton Entrar;
    public static javax.swing.JLabel NoPass;
    public static javax.swing.JLabel NoUsuario;
    public static javax.swing.JLabel OlvidPass;
    public static javax.swing.JLabel Registrarse;
    public static javax.swing.JPasswordField TxtPass;
    public static javax.swing.JTextField TxtUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    // End of variables declaration//GEN-END:variables
}
